// <auto-generated />
namespace DesafioAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ROLLBACK0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ROLLBACK0));
        
        string IMigrationMetadata.Id
        {
            get { return "202207061513088_ROLLBACK0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
